#!/usr/bin/env python3
"""Regenerability gate: every generated file in this repository is the file its
generator produces, checked by producing it.

What went wrong without it
--------------------------
The corpus publishes a determinism recipe. Both vector indexes say the set
regenerates byte-identically from the generator beside it, and the manifest's own
docstring says the same. Nothing ever checked it. Seven vector files and seven
manifest entries were once committed with no builder and no index row behind
them, and the tree stayed green for a day: the harness replayed all of them and
passed, because the harness reads the committed bytes and the manifest, and both
of those had been written by hand. The defect surfaced only when someone ran the
manifest generator, whose closure check refused. A published recipe that nobody
executes is a claim, and this repository has spent its history removing those.

Three separate things were wrong in that one commit and only the third was
visible to any existing check: five of the files carried a different constant set
from the generator they were filed beside, three of them carried a record whose
signature does not verify, and the manifest had been rewritten in a different
order from the one its generator emits. All three are the same defect --
committed bytes that no generator produces -- and this gate is the shape of check
that catches all three at once, because it does not inspect the bytes at all. It
regenerates them and compares.

How it works
------------
The tracked tree is copied into a temporary directory, the generators are run
there in dependency order, and every file they own is compared with the committed
one. Nothing in the repository is written. The copy is what makes the comparison
honest: running the generators in place would overwrite the very bytes the gate
is supposed to be comparing against, so a run would always agree with itself.

What "own" means is declared rather than inferred, in OWNED below, and a file
matching one of those patterns in the committed tree and missing from the
regenerated one fails just as loudly as one whose bytes differ. That direction is
the one that caught nothing before: a vector file with no builder is not a
mismatch, it is an absence, and an absence is what a checksum comparison over the
files that were produced will never see.

Two generated artifacts are deliberately NOT listed here.
``vectors/accept/INDEX.md`` is authored by hand rather than emitted, and it is
tied to the corpus from both ends anyway: ``vectors/gen_manifest.py`` refuses
when a row and a file disagree, and ``scripts/count-gate.py`` refuses when a row
and the manifest do. ``packaging/conformance-report.json`` is a run artifact
rather than a source, and the run that writes it is its own check.

Usage:
    python3 scripts/regenerability-gate.py
    python3 scripts/regenerability-gate.py --root <tree>   (for its own tests)
Exit 0 when every generated file regenerates byte-identically; 1 otherwise.
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The generators, in dependency order: the manifest is derived from the indexes,
# and the reject index is written by the reject generator, so the manifest runs
# last or it derives from an index one revision behind.
GENERATORS = (
    "vectors/accept/gen_valid_vectors.py",
    "vectors/reject/gen_invalid_vectors.py",
    "vectors/gen_manifest.py",
)

# Every file a generator above is responsible for, as a directory and a glob.
# Declared rather than discovered: a gate that compared whatever the generators
# happened to write could not tell a file that was not regenerated from a file
# that was never meant to be.
OWNED = (
    ("vectors/accept", "ok-*.json"),
    ("vectors/reject", "bad-*.json"),
    ("vectors/reject", "INDEX.md"),
    ("vectors", "MANIFEST.json"),
)

REMEDY = (
    "A committed file that its generator does not reproduce cannot be "
    "regenerated by anyone, and the determinism recipe both vector indexes "
    "publish is false for it. Fix the generator so it emits the committed bytes, "
    "or -- if the committed bytes are the wrong ones -- regenerate them, say so, "
    "and re-vendor the consumer copies with "
    "scripts/consumer-lag-gate.py --sync. Never edit a generated file by hand: "
    "the next run of its generator silently reverts it."
)


def tracked(root: Path) -> list[str]:
    listed = subprocess.run(
        ["git", "-C", str(root), "ls-files"],
        capture_output=True,
        text=True,
        check=True,
    )
    return listed.stdout.split()


def stage(root: Path, destination: Path) -> None:
    """Copy the tracked tree, so the generators write over a copy and not a source."""
    for rel in tracked(root):
        origin = root / rel
        if not origin.is_file():
            continue
        target = destination / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(origin, target)


def wipe(destination: Path) -> None:
    """Delete every owned file from the copy before the generators run.

    Without this the gate has a blind spot in the exact shape of the defect it
    exists to catch. The copy starts as the committed tree, so a file the
    generators never touch is still sitting there when the comparison runs, and
    it compares equal to itself: a vector with no builder passes, silently,
    because nothing distinguishes 'regenerated identically' from 'never written'.
    Emptying the owned set first makes absence visible as absence.
    """
    for rel, path in owned_files(destination).items():
        del rel
        path.unlink()


def regenerate(destination: Path) -> list[str]:
    failures: list[str] = []
    for rel in GENERATORS:
        proc = subprocess.run(
            [sys.executable, str(destination / rel)],
            cwd=str(destination),
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            failures.append(
                f"{rel}: exited {proc.returncode} rather than regenerating its "
                f"files.\n{(proc.stdout + proc.stderr).strip()}"
            )
    return failures


def owned_files(root: Path) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for directory, pattern in OWNED:
        for path in sorted((root / directory).glob(pattern)):
            found[f"{directory}/{path.name}"] = path
    return found


def compare(root: Path, destination: Path) -> list[str]:
    committed = owned_files(root)
    regenerated = owned_files(destination)
    failures: list[str] = []
    for rel in sorted(set(committed) - set(regenerated)):
        failures.append(
            f"{rel} is committed and no generator produced it. A file no generator "
            "writes is a file nobody can reproduce, and it is how five vectors "
            "entered this corpus."
        )
    for rel in sorted(set(regenerated) - set(committed)):
        failures.append(
            f"{rel} is produced by a generator and is not committed, so the "
            "corpus a reader clones is smaller than the one the generators build."
        )
    for rel in sorted(set(committed) & set(regenerated)):
        if not filecmp.cmp(committed[rel], regenerated[rel], shallow=False):
            failures.append(f"{rel} differs from what its generator produces.")
    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="every generated file is the file its generator produces"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="the tree to check; a staged copy when this gate's own tests run it",
    )
    root = parser.parse_args(argv[1:]).root.resolve()

    with tempfile.TemporaryDirectory() as raw:
        destination = Path(raw) / "regenerated"
        destination.mkdir()
        stage(root, destination)
        wipe(destination)
        failures = regenerate(destination)
        failures.extend(compare(root, destination))
        checked = len(owned_files(root))

    if failures:
        print(
            f"FAIL: {len(failures)} generated file(s) or generator(s) do not hold:",
            file=sys.stderr,
        )
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        print(f"\n{REMEDY}", file=sys.stderr)
        return 1
    print(
        f"OK: all {checked} generated file(s) regenerate byte-identically from "
        f"the {len(GENERATORS)} generators that own them."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
